/* Browser capture requires an explicit local permission and a separate send action. */
'use strict';
const el=id=>document.getElementById(id);
const video=el('video'),view=el('view'),ctx=view.getContext('2d');
const raw=document.createElement('canvas'),rawCtx=raw.getContext('2d');
let config=null,stream=null,socket=null,active=false,used=false,tracks=[],timer=null,watchdog=null,generation=0;
function notify(type,extra={}){parent.postMessage({isStreamlitMessage:true,type,...extra},location.origin);}
function height(){notify('streamlit:setFrameHeight',{height:document.body.scrollHeight+10});}
function status(text,error=false){el('status').textContent=text;el('status').className=error?'error':'';height();}
function gate(){return {axis:el('axis').value,position:Number(el('position').value)/100,positive_entry:el('direction').value==='true'};}
function labels(){const horizontal=el('axis').value==='y';el('direction').options[0].textContent=horizontal?'De cima para baixo':'Esquerda → direita';el('direction').options[1].textContent=horizontal?'De baixo para cima':'Direita → esquerda';}
function lockGate(locked){['axis','position','direction'].forEach(id=>el(id).disabled=locked);}
function cleanup(message,error=false){generation++;active=false;clearTimeout(timer);clearTimeout(watchdog);tracks=[];if(socket){const old=socket;socket=null;old.onclose=null;old.onerror=null;old.close();}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}video.srcObject=null;ctx.clearRect(0,0,view.width,view.height);el('empty').hidden=false;el('start').disabled=true;el('stop').disabled=true;el('preview').disabled=used;el('device').disabled=true;el('renew').hidden=!used;lockGate(false);if(message)status(message,error);}
async function preview(){cleanup();if(!navigator.mediaDevices?.getUserMedia){status('Este navegador não permite câmera aqui. Abra o painel em Chrome, Edge ou Firefox atualizado, usando HTTPS.',true);return;}const mine=++generation;el('preview').disabled=true;status('Aguardando sua permissão para usar a câmera…');try{const id=el('device').value;const capture=await navigator.mediaDevices.getUserMedia({audio:false,video:{...(id?{deviceId:{exact:id}}:{}),width:{ideal:640},height:{ideal:480},frameRate:{ideal:10,max:15}}});if(mine!==generation){capture.getTracks().forEach(t=>t.stop());return;}stream=capture;video.srcObject=stream;await video.play();if(mine!==generation)return;const scale=Math.min(640/video.videoWidth,480/video.videoHeight,1);view.width=raw.width=Math.round(video.videoWidth*scale);view.height=raw.height=Math.round(video.videoHeight*scale);const selected=stream.getVideoTracks()[0].getSettings().deviceId;const devices=await navigator.mediaDevices.enumerateDevices();el('device').replaceChildren();devices.filter(d=>d.kind==='videoinput').forEach((d,i)=>{const option=new Option(d.label||`Webcam ${i+1}`,d.deviceId);option.selected=d.deviceId===selected;el('device').add(option);});el('device').disabled=false;el('start').disabled=!config||used;el('stop').disabled=false;el('empty').hidden=true;stream.getVideoTracks()[0].addEventListener('ended',()=>cleanup('A câmera foi desconectada. Prepare uma nova sessão.',true),{once:true});status('Prévia local ativa. Ajuste a linha; sua imagem ainda não está sendo enviada.');}catch(error){cleanup(error.name==='NotAllowedError'?'Permissão negada. Libere a câmera nas permissões deste site e tente novamente.':error.name==='NotFoundError'?'Nenhuma webcam encontrada neste computador.':'Não foi possível abrir a webcam. Feche outros aplicativos que estejam usando a câmera.',true);}}
function draw(){requestAnimationFrame(draw);if(!stream||video.readyState<2)return;ctx.drawImage(video,0,0,view.width,view.height);const g=gate();const px=g.position*view.width,py=g.position*view.height;ctx.strokeStyle='#facc15';ctx.lineWidth=3;ctx.beginPath();if(g.axis==='x'){ctx.moveTo(px,0);ctx.lineTo(px,view.height);}else{ctx.moveTo(0,py);ctx.lineTo(view.width,py);}ctx.stroke();ctx.fillStyle='#facc15';ctx.font='bold 17px system-ui';const direction=g.axis==='x'?(g.positive_entry?'Entrada →':'← Entrada'):(g.positive_entry?'Entrada ↓':'Entrada ↑');ctx.fillText(direction,12,26);for(const track of tracks){const [x1,y1,x2,y2]=track.box;ctx.strokeStyle='#4ade80';ctx.lineWidth=2;ctx.strokeRect(x1*view.width,y1*view.height,(x2-x1)*view.width,(y2-y1)*view.height);ctx.fillStyle='#4ade80';ctx.fillText(`Pessoa ${track.id}`,x1*view.width,Math.max(20,y1*view.height-5));}}
function awaitResponse(){clearTimeout(watchdog);watchdog=setTimeout(()=>cleanup('A conexão parou de responder. A câmera foi desligada; prepare uma nova sessão.',true),8000);}
function sendFrame(){if(!active||!stream||socket?.readyState!==WebSocket.OPEN)return;const mine=generation;rawCtx.drawImage(video,0,0,raw.width,raw.height);raw.toBlob(blob=>{if(!active||mine!==generation||socket?.readyState!==WebSocket.OPEN)return;if(!blob||blob.size>160000||socket.bufferedAmount>160000){cleanup('A imagem excedeu o limite de transmissão. Prepare uma nova sessão.',true);return;}socket.send(blob);awaitResponse();},'image/jpeg',0.65);}
function start(){if(!stream||!config||used)return;used=true;active=true;el('start').disabled=true;el('preview').disabled=true;el('device').disabled=true;lockGate(true);el('entries').textContent='0';el('exits').textContent='0';status('Conectando à análise na nuvem…');const ws=new WebSocket(`wss://${location.host}/api/browser/ws`);socket=ws;awaitResponse();ws.onopen=()=>ws.send(JSON.stringify({token:config.token,gate:gate()}));ws.onmessage=event=>{if(socket!==ws)return;let message;try{message=JSON.parse(event.data);}catch{cleanup('Resposta inválida do servidor.',true);return;}clearTimeout(watchdog);if(message.type==='error'){cleanup(message.message,true);return;}if(message.type==='ready'){status('Monitoramento ativo. Imagens enviadas à nuvem; sem áudio.');sendFrame();}else if(message.type==='result'){tracks=message.tracks;el('entries').textContent=message.entries;el('exits').textContent=message.exits;el('performance').textContent=`Contagem confirmada pelo servidor. Processamento: ${message.processing_ms} ms por imagem. Totais desta sessão; histórico em Entradas e Saídas. Mantenha a página ativa.`;timer=setTimeout(sendFrame,30);}};ws.onerror=()=>{if(socket===ws)cleanup('Não foi possível conectar à análise. Prepare uma nova sessão e tente novamente.',true);};ws.onclose=()=>{if(socket===ws)cleanup('A sessão foi encerrada. Prepare uma nova sessão para continuar.',true);};}
el('preview').onclick=preview;el('device').onchange=preview;el('start').onclick=start;el('stop').onclick=()=>cleanup('Câmera desligada. As contagens já confirmadas foram preservadas.');el('axis').onchange=labels;el('renew').onclick=()=>{cleanup();el('renew').disabled=true;status('Preparando nova sessão…');notify('streamlit:setComponentValue',{value:{action:'renew',grant_id:config.grant_id},dataType:'json'});};view.onclick=event=>{if(active||!stream)return;const r=view.getBoundingClientRect();const fraction=gate().axis==='x'?(event.clientX-r.left)/r.width:(event.clientY-r.top)/r.height;el('position').value=String(Math.round(Math.min(.85,Math.max(.15,fraction))*100));};
window.addEventListener('message',event=>{if(event.source!==parent||event.origin!==location.origin||event.data?.type!=='streamlit:render')return;const next=event.data.args;if(!config||next.grant_id!==config.grant_id){cleanup();config=next;used=false;el('preview').disabled=false;el('renew').hidden=true;el('renew').disabled=false;el('axis').value=next.gate.axis;el('position').value=String(next.gate.position*100);el('direction').value=String(Boolean(next.gate.positive_entry));labels();status('Câmera desligada. Clique em Ligar prévia para permitir o acesso.');}const theme=event.data.theme;if(theme){document.documentElement.style.setProperty('--bg',theme.backgroundColor);document.documentElement.style.setProperty('--text',theme.textColor);}height();});
window.addEventListener('pagehide',()=>cleanup());window.addEventListener('beforeunload',()=>cleanup());document.addEventListener('visibilitychange',()=>{if(document.hidden&&stream)cleanup('A página ficou inativa e a câmera foi desligada. Retome a prévia para continuar.');});new ResizeObserver(height).observe(document.body);notify('streamlit:componentReady',{apiVersion:1});draw();height();
